// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eem_search_cpp
DataFrame eem_search_cpp(NumericMatrix expr, List geneSets, double relativeRadius, double pvalue1Cutoff, int itr, int minGeneSetSize, int maxGeneSetSize, int coreGeneSize);
RcppExport SEXP _eemr_eem_search_cpp(SEXP exprSEXP, SEXP geneSetsSEXP, SEXP relativeRadiusSEXP, SEXP pvalue1CutoffSEXP, SEXP itrSEXP, SEXP minGeneSetSizeSEXP, SEXP maxGeneSetSizeSEXP, SEXP coreGeneSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type geneSets(geneSetsSEXP);
    Rcpp::traits::input_parameter< double >::type relativeRadius(relativeRadiusSEXP);
    Rcpp::traits::input_parameter< double >::type pvalue1Cutoff(pvalue1CutoffSEXP);
    Rcpp::traits::input_parameter< int >::type itr(itrSEXP);
    Rcpp::traits::input_parameter< int >::type minGeneSetSize(minGeneSetSizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxGeneSetSize(maxGeneSetSizeSEXP);
    Rcpp::traits::input_parameter< int >::type coreGeneSize(coreGeneSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(eem_search_cpp(expr, geneSets, relativeRadius, pvalue1Cutoff, itr, minGeneSetSize, maxGeneSetSize, coreGeneSize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eemr_eem_search_cpp", (DL_FUNC) &_eemr_eem_search_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_eemr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
