# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eem_search_cpp <- function(expr, geneSets, relativeRadius, pvalue1Cutoff, itr, minGeneSetSize, maxGeneSetSize, coreGeneSize) {
    .Call(`_eemr_eem_search_cpp`, expr, geneSets, relativeRadius, pvalue1Cutoff, itr, minGeneSetSize, maxGeneSetSize, coreGeneSize)
}

